CREATE DATABASE TASTY_BYTES_CLONE
CLONE TASTY_BYTES;

CREATE TABLE tasty_bytes.raw_pos.truck_clone
CLONE tasty_bytes.raw_pos.truck;

SELECT * FROM TASTY_BYTES.INFORMATION_SCHEMA.TABLE_STORAGE_METRICS
WHERE (TABLE_NAME = 'TRUCK_CLONE' OR TABLE_NAME = 'TRUCK')
AND TABLE_CATALOG = 'TASTY_BYTES';