SHOW FUNCTIONS;

CREATE FUNCTION min_menu_price()
RETURNS NUMBER(5,2)
AS $$
SELECT MIN(SALE_PRICE_USD) FROM TASTY_BYTES.RAW_POS.MENU
$$;

SELECT min_menu_price();

CREATE FUNCTION menu_prices_below(price_ceiling NUMBER)
RETURNS TABLE (item VARCHAR, price NUMBER) AS
$$
SELECT MENU_ITEM_NAME, SALE_PRICE_USD
    FROM TASTY_BYTES.RAW_POS.MENU
    WHERE SALE_PRICE_USD < price_ceiling
    ORDER BY 2 DESC
$$;
SELECT * FROM TABLE(menu_prices_below(3));