CREATE ROLE tasty_role;

 SHOW GRANTS TO ROLE tasty_role;

 GRANT CREATE DATABASE ON ACCOUNT TO tasty_role;

 SELECT CURRENT_USER;

 GRANT ROLE tasty_role TO USER ANISHKARIM;
 USE ROLE TASTY_ROLE;

 CREATE OR REPLACE WAREHOUSE tasty_test_wh;

 USE ROLE ACCOUNTADMIN;

 SHOW GRANTS TO USER ANISHKARIM;

 SHOW GRANTS TO ROLE USERADMIN;