CREATE DATABASE tasty_bytes_clone CLONE tasty_bytes;

CREATE OR REPLACE PROCEDURE increase_prices()
RETURNS BOOLEAN
LANGUAGE SQL
AS $$
BEGIN
UPDATE TASTY_BYTES_CLONE.RAW_POS.MENU
    SET SALE_PRICE_USD = menu.SALE_PRICE_USD + 1;

END;
$$;

CALL increase_prices();
DESCRIBE PROCEDURE increase_prices();

SELECT * FROM TASTY_BYTES_CLONE.RAW_POS.MENU
WHERE MENU_ITEM_NAME='Mango Sticky Rice';

CREATE OR REPLACE PROCEDURE decrease_mango_sticky_rice_price()
RETURNS BOOLEAN
LANGUAGE SQL
AS $$
BEGIN
UPDATE TASTY_BYTES_CLONE.RAW_POS.MENU
    SET SALE_PRICE_USD = MENU.SALE_PRICE_USD -1
WHERE MENU_ITEM_NAME='Mango Sticky Rice';
END;
$$;

SHOW PROCEDURES;